name: build

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.9", "3.8", "3.7"]
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install --no-ansi --no-root --no-interaction --only build
          poetry run pip install .

      - name: Lint
        run: poetry run poe lint

      - name: Test
        run: poetry run pytest
